### ISSUE TITLE
Unable to Locate test-simple.py

### ISSUE THREAD

**Issue by kxs8997** [mobarakol/DARES#1]
Hello!
I would like to predict scaled disparity for a folder of images. But I was unable to locate the test_simple.py script.

Appreciate your help!

CUDA_VISIBLE_DEVICES=0 python test_simple.py --model_path <your_model_path> --image_path <your_image_or_folder_path>

**Comment by Mona-ShZeinoddin** [comment]
Hello 
Thank you for pointing this out and for your interest in our work,
The script has been added.
