### ISSUE TITLE
Attempting to train_end_to_end, but missing file?

### ISSUE THREAD

**Issue by reubendocea** [mobarakol/DARES#2]
Hi, 

cool work !!

I'm wanting to try out the training pipeline, but I can't find the "extract_left_frames.py" file that is mentioned in the README?

Also, I see in the README that the SERV-CT and EndoSLAM datasets are mentioned. But I don't see them used?

Thanks a lot for releasing the code :) 

Reuben

**Comment by mobarakol** [comment]
Dear Reuben,

Thanks for reaching out and pointing the inconsistencies in the readme file. I have fixed those issues. Please check the updated readme file. More specifically, you can find the "extract_left_frames.py"  at https://github.com/ShuweiShao/AF-SfMLearner/blob/main/extract_left_frames.py

Best,
Mobarak
